Remove patches, fix build
[ 2046s] ../drivers/usb/host/xen-hcd.c:58:10: fatal error: xen/interface/io/usbif.h: No such file or directory
[ 2046s]    58 | #include <xen/interface/io/usbif.h>
[ 2046s]       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~

Remove:
 * patches.suse/0002-usb-Introduce-Xen-pvUSB-frontend-xen-hcd.patch
 * patches.suse/suse-hv-guest-os-id.patch

Signed-off-by: David Sterba <dsterba@suse.com>